### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by JustBrenkman** [BYU-IGVC/ros_igvc#5]
Create an API to abstract the ROS system

**Comment by bfotheri** [comment]
Hey, we'll address this on Monday I'm sure but with the ROS API I was wondering what we will do with nodes that have a pub and sub, or multiple pubs and multiple subs.

**Comment by idraper** [comment]
As you said, we can talk about this Monday, but there shouldn't be any problems with having any combination since it is a class you can create as many as you need of either and send/receive from any of them in the same script.

**Comment by bfotheri** [comment]
True, but each pub and sub inherits from handler which is itself a node
which means two pubs and subs would be four nodes which seems unecessary.
Let me take another look though before Monday though to be sure.

**Comment by idraper** [comment]
Yes, that is correct. And yes, it is definitely overkill and not what we want. However, it will work for now until I get the rest of the library up and running. It is a temporary solution while I get the API working with more applicable stuff. The entire point of the API is make interacting with ROS easier, so I just started with the most basic.

**Comment by idraper** [comment]
Although, I'm actually thinking this might be the only way to do it. I thought this would be very inefficient, but it seems it is how ROS was designed to operate since this is all multi-threaded just for this reason.

See:
http://wiki.ros.org/ROS/Concepts under the Topics section

After looking a bit as well it doesn't seem there is a fundamental alternative except for Services, which are a special case (and I will add those soon).

**Comment by JustBrenkman** [comment]
Each ROS node can have multiple Publishers and Subscribers. The API won't work under those circumstances. I tried and gave a ROS error saying the node was already initialized under a different name

**Comment by idraper** [comment]
My bad, I didn't realize that only one node was initialized even with multiple publishers/subscribers. I will create a hotfix tonight.
